name: "ci"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "*/5 * * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: build
        run: ./.github/build.sh

      - name: fetch
        run: /tmp/beauty

      - name: commit
        run: /tmp/commiter -add . -msg "fetch by action"
