name: "ci"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "*/5 * * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: build
        run: ./.github/build.sh

      - name: fetch
        run: /tmp/fetch && /tmp/send_msg
        env:
          LARK_WEBHOOK_URL_1: ${{ secrets.LARK_WEBHOOK_URL_1 }}
          LARK_APP_ID_1: ${{ srcrets.LARK_APP_ID_1 }}
          LARK_APP_SECRET_1: ${{ secrets.LARK_APP_SECRET_1 }}

      - name: commit
        run: /tmp/commiter -add . -msg "fetch by action"
